### PR TITLE
files

### PR DESCRIPTION
**Pull request by claesiacosta**

### CODE REVIEW

**Comment by jirka-x1** [comment]
It is not possible to comment on the jupyter notebooks directly, so I will add the comments here.

**Comment by jirka-x1** [comment]
1. You should use `with` for opening resources.
2. Do not rely on global variables if not necessary (`writer1`, `writer`).

Typically, this is not a big problem in jupyter notebooks, but it is better to write it correctly from scratch.

In `data_collection.ipynb`
```
with open('tweets_all.csv', 'w', encoding='UTF8') as f1, \
open('tweets.csv', 'w', encoding='UTF8') as f:
   writer1 = csv.writer(f1)
   writer = csv.writer(f)
   writer1.writerow(header1)
   writer.writerow(header)
   
   extract_tweet(writer, writer1)
   
```
In `classification.ipynb`:
```
classify(data)
```

**Comment by jirka-x1** [comment]
You define `maxTweets` but then test for 1000 directly

**Comment by jirka-x1** [comment]
Add comment to the top of each notebook explaining what the notebook does.

**Comment by jirka-x1** [comment]
Use English in comments and names of variables (palavra etc).

**Comment by claesiacosta** [comment]
I commited and pushed with the fixed changes

**Review by jirka-x1 — APPROVED** [review]

**Pull request merged**
